import { GurmukhiLetter } from "./types";
export const GURMUKHI_LETTERS: GurmukhiLetter[] = [
  {
    letter: "ੳ",
    transliteration: "Oora",
    audioSrc: "/assets/35lettersAudios/01 ੳ.m4a",
    description: "ੳ ਅ ੲ can never be used in word in their pure form. They need to have a matra(vowel) to be used. Might not make sense yet",
  },
  {
    letter: "ਅ",
    transliteration: "Aira",
    audioSrc: "/assets/35lettersAudios/02 ਅ.m4a",
    description: "Second letter of the Gurmukhi alphabet",
  },
  {
    letter: "ੲ",
    transliteration: "Iri",
    audioSrc: "/assets/35lettersAudios/03 ੲ.m4a",
    description: "Third letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਸ",
    transliteration: "Sassa",
    audioSrc: "/assets/35lettersAudios/04 ਸ.m4a",
    description: "Fourth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਹ",
    transliteration: "Haha",
    audioSrc: "/assets/35lettersAudios/05 ਹ.m4a",
    description: "Fifth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਕ",
    transliteration: "Kakka",
    audioSrc: "/assets/35lettersAudios/06 ਕ.m4a",
    description: "Sixth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਖ",
    transliteration: "Khakha",
    audioSrc: "/assets/35lettersAudios/07 ਖ.m4a",
    description: "Seventh letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਗ",
    transliteration: "Gagga",
    audioSrc: "/assets/35lettersAudios/08 ਗ.m4a",
    description: "Eighth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਘ",
    transliteration: "Ghagha",
    audioSrc: "/assets/35lettersAudios/09 ਘ.m4a",
    description: "Ninth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਙ",
    transliteration: "Nga",
    audioSrc: "/assets/35lettersAudios/10.m4a",
    description: "Tenth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਚ",
    transliteration: "Chacha",
    audioSrc: "/assets/35lettersAudios/11 ਚ.m4a",
    description: "Eleventh letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਛ",
    transliteration: "Chhachha",
    audioSrc: "/assets/35lettersAudios/12 ਛ.m4a",
    description: "Twelfth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਜ",
    transliteration: "Jaja",
    audioSrc: "/assets/35lettersAudios/13 ਜ.m4a",
    description: "Thirteenth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਝ",
    transliteration: "Jhajha",
    audioSrc: "/assets/35lettersAudios/14 ਝ.m4a",
    description: "Fourteenth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਞ",
    transliteration: "Nyanya",
    audioSrc: "/assets/35lettersAudios/15.m4a",
    description: "Fifteenth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਟ",
    transliteration: "Tainka",
    audioSrc: "/assets/35lettersAudios/16 ਟ.m4a",
    description: "Sixteenth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਠ",
    transliteration: "Thaitha",
    audioSrc: "/assets/35lettersAudios/17 ਠ.m4a",
    description: "Seventeenth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਡ",
    transliteration: "Dada",
    audioSrc: "/assets/35lettersAudios/18 ਡ.m4a",
    description: "Eighteenth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਢ",
    transliteration: "Dhaddha",
    audioSrc: "/assets/35lettersAudios/19 ਢ.m4a",
    description: "Nineteenth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਣ",
    transliteration: "Nana",
    audioSrc: "/assets/35lettersAudios/20 ਣ.m4a",
    description: "Twentieth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਤ",
    transliteration: "Tatta",
    audioSrc: "/assets/35lettersAudios/21 ਤ.m4a",
    description: "Twenty-first letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਥ",
    transliteration: "Thatha",
    audioSrc: "/assets/35lettersAudios/22 ਥ.m4a",
    description: "Twenty-second letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਦ",
    transliteration: "Dadda",
    audioSrc: "/assets/35lettersAudios/23 ਦ.m4a",
    description: "Twenty-third letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਧ",
    transliteration: "Dhaddha",
    audioSrc: "/assets/35lettersAudios/24 ਧ.m4a",
    description: "Twenty-fourth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਨ",
    transliteration: "Nanna",
    audioSrc: "/assets/35lettersAudios/25 ਨ.m4a",
    description: "Twenty-fifth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਪ",
    transliteration: "Pappa",
    audioSrc: "/assets/35lettersAudios/26 ਪ.m4a",
    description: "Twenty-sixth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਫ",
    transliteration: "Phaffa",
    audioSrc: "/assets/35lettersAudios/27 ਫ.m4a",
    description: "Twenty-seventh letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਬ",
    transliteration: "Babba",
    audioSrc: "/assets/35lettersAudios/28 ਬ.m4a",
    description: "Twenty-eighth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਭ",
    transliteration: "Bhabbha",
    audioSrc: "/assets/35lettersAudios/29 ਭ.m4a",
    description: "Twenty-ninth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਮ",
    transliteration: "Mamma",
    audioSrc: "/assets/35lettersAudios/30 ਮ.m4a",
    description: "Thirtieth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਯ",
    transliteration: "Yayya",
    audioSrc: "/assets/35lettersAudios/31 ਯ.m4a",
    description: "Thirty-first letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਰ",
    transliteration: "Rarra",
    audioSrc: "/assets/35lettersAudios/32 ਰ.m4a",
    description: "Thirty-second letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਲ",
    transliteration: "Lalla",
    audioSrc: "/assets/35lettersAudios/33 ਲ.m4a",
    description: "Thirty-third letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਵ",
    transliteration: "Vava",
    audioSrc: "/assets/35lettersAudios/34 ਵ.m4a",
    description: "Thirty-fourth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ੜ",
    transliteration: "Rara",
    audioSrc: "/assets/35lettersAudios/35 ੜ.m4a",
    description: "Thirty-fifth letter of the Gurmukhi alphabet",
  },
];
