import { GurmukhiLetter } from "./types";
export const GURMUKHI_LETTERS: GurmukhiLetter[] = [
  {
    letter: "ੳ",
    transliteration: "Oora",
    audioSrc: "/audio/oora.mp3",
    description: "First letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਅ",
    transliteration: "Aira",
    audioSrc: "/audio/aira.mp3",
    description: "Second letter of the Gurmukhi alphabet",
  },
  {
    letter: "ੲ",
    transliteration: "Iri",
    audioSrc: "/audio/iri.mp3",
    description: "Third letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਸ",
    transliteration: "Sassa",
    audioSrc: "/audio/sassa.mp3",
    description: "Fourth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਹ",
    transliteration: "Haha",
    audioSrc: "/audio/haha.mp3",
    description: "Fifth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਕ",
    transliteration: "Kakka",
    audioSrc: "/audio/kakka.mp3",
    description: "Sixth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਖ",
    transliteration: "Khakha",
    audioSrc: "/audio/khakha.mp3",
    description: "Seventh letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਗ",
    transliteration: "Gagga",
    audioSrc: "/audio/gagga.mp3",
    description: "Eighth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਘ",
    transliteration: "Ghagha",
    audioSrc: "/audio/ghagha.mp3",
    description: "Ninth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਙ",
    transliteration: "Nga",
    audioSrc: "/audio/nga.mp3",
    description: "Tenth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਚ",
    transliteration: "Chacha",
    audioSrc: "/audio/chacha.mp3",
    description: "Eleventh letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਛ",
    transliteration: "Chhachha",
    audioSrc: "/audio/chhachha.mp3",
    description: "Twelfth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਜ",
    transliteration: "Jaja",
    audioSrc: "/audio/jaja.mp3",
    description: "Thirteenth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਝ",
    transliteration: "Jhajha",
    audioSrc: "/audio/jhajha.mp3",
    description: "Fourteenth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਞ",
    transliteration: "Nyanya",
    audioSrc: "/audio/nyanya.mp3",
    description: "Fifteenth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਟ",
    transliteration: "Tainka",
    audioSrc: "/audio/tainka.mp3",
    description: "Sixteenth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਠ",
    transliteration: "Thaitha",
    audioSrc: "/audio/thaitha.mp3",
    description: "Seventeenth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਡ",
    transliteration: "Dada",
    audioSrc: "/audio/dada.mp3",
    description: "Eighteenth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਢ",
    transliteration: "Dhaddha",
    audioSrc: "/audio/dhaddha.mp3",
    description: "Nineteenth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਣ",
    transliteration: "Nana",
    audioSrc: "/audio/nana.mp3",
    description: "Twentieth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਤ",
    transliteration: "Tatta",
    audioSrc: "/audio/tatta.mp3",
    description: "Twenty-first letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਥ",
    transliteration: "Thatha",
    audioSrc: "/audio/thatha.mp3",
    description: "Twenty-second letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਦ",
    transliteration: "Dadda",
    audioSrc: "/audio/dadda.mp3",
    description: "Twenty-third letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਧ",
    transliteration: "Dhaddha",
    audioSrc: "/audio/dhaddha.mp3",
    description: "Twenty-fourth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਨ",
    transliteration: "Nanna",
    audioSrc: "/audio/nanna.mp3",
    description: "Twenty-fifth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਪ",
    transliteration: "Pappa",
    audioSrc: "/audio/pappa.mp3",
    description: "Twenty-sixth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਫ",
    transliteration: "Phaffa",
    audioSrc: "/audio/phaffa.mp3",
    description: "Twenty-seventh letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਬ",
    transliteration: "Babba",
    audioSrc: "/audio/babba.mp3",
    description: "Twenty-eighth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਭ",
    transliteration: "Bhabbha",
    audioSrc: "/audio/bhabbha.mp3",
    description: "Twenty-ninth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਮ",
    transliteration: "Mamma",
    audioSrc: "/audio/mamma.mp3",
    description: "Thirtieth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਯ",
    transliteration: "Yayya",
    audioSrc: "/audio/yayya.mp3",
    description: "Thirty-first letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਰ",
    transliteration: "Rarra",
    audioSrc: "/audio/rarra.mp3",
    description: "Thirty-second letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਲ",
    transliteration: "Lalla",
    audioSrc: "/audio/lalla.mp3",
    description: "Thirty-third letter of the Gurmukhi alphabet",
  },
  {
    letter: "ਵ",
    transliteration: "Vava",
    audioSrc: "/audio/vava.mp3",
    description: "Thirty-fourth letter of the Gurmukhi alphabet",
  },
  {
    letter: "ੜ",
    transliteration: "Rara",
    audioSrc: "/audio/rara.mp3",
    description: "Thirty-fifth letter of the Gurmukhi alphabet",
  },
];
